### ISSUE TITLE
[Bug] ...Portal wont form

### ISSUE THREAD

**Issue by Mannhood** [SuperMartijn642/Wormhole#13]
**Version Info**
- Minecraft, ...1.16.5
- Wormhole, wormhole-1.1.4-mc1.16.3

**Description of the Bug**
...
I have manyportals set up but recently some portals deactivate and when i try to reform them then i get invalid portal construction. used portal frames allso do not stack with ones that i have had placed once. any new portals allso mostly fail sometimes i get lucky and they form and can be activated
**Steps to Reproduce**
...happens in DW20 modpack v1.7 & 1.6.1
 I can provide world download

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Are you sure the blocks inside the portal frame area are actually empty?
Lightest lamps for example places invisible light sources around, which can stop the portal from activating. Simply placing and breaking dirt should fix it in that case.

Also the portal frame blocks not stacking will be fixed in the next update.

**Comment by SuperMartijn642** [comment]
I can't help without more info.
Feel free to comment and I will reopen the issue.

**Comment by ShadowJonathan** [comment]
This issue helped me, we have "feral torches" in our modpack that places invisible lights, and i was really confused why the portal stopped reactivating after a moment, thanks!

**Comment by SuperMartijn642** [comment]
Yeah that can be annoying sometimes, especially when there's no indication that there's a light source there.
