### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by xJohnx117** [SuperMartijn642/Wormhole#47]
**Version Info**
- Minecraft, 1.18.2
- Wormhole, 1.1.12

**Description of the Bug**
Targets get mixed up when there is more than 1 target cell.

**Steps to Reproduce**
Same as the bug description

**Screenshots**
None, unfortunately

**Comment by SuperMartijn642** [comment]
I am not sure what you mean. What do you mean by 'mixed up'? When does this happen?

**Comment by xJohnx117** [comment]
Well the portal would pick the wrong target, and the target would get moved uncontrollably, and pretty much renders the wormhole useless.

**Comment by SuperMartijn642** [comment]
Wormholes with multiple targets seem to work just fine. I select and activate different targets and I can move the up or down with any issues.
Could you provide more precise steps to reproduce the issue?

**Comment by xJohnx117** [comment]
I'm talking about multiple target cells, not multiple targets, with one cell, it works fine, but if there's more than 1, the target selection... breaks.

**Comment by SuperMartijn642** [comment]
It appears to work fine:

https://github.com/SuperMartijn642/Wormhole/assets/12382965/8a57efb4-3167-483f-85ac-c9adb0c9246f

**Comment by SuperMartijn642** [comment]
Since what you reported is very similar to the issue in #53, I will assume that you were also using Lithium. As concluded in that other issue, a mixin from Lithium caused a desync between the server and client.
I added a workaround in Wormhole version 1.1.14 which fixes it.

If you were not using Lithium, let me know.
